### ISSUE TITLE
set alternative font for Prefix chars

### ISSUE THREAD

**Issue by Ramiferous** [jszczerbinsky/ptSh#2]
Is is possible to set an alternative font for the prefix characters from within the config without having to change my terminal font to something that supports displaying these characters?

**Comment by jszczerbinsky** [comment]
Unfortunately terminals can't display multiple fonts at once (or rather I don't know any, that can do this), but I'm pretty sure, that your font can display some special chars. Check out this script:

```shell

#!/bin/bash

x=(0 1 2 3 4 5 6 7 8 9 A B C D E F)
for a in {0..15}; do for b in {0..15}; do for c in {0..15}; do
	[[ $a -eq 0 && $b -eq 0 && $c -lt 2 ]] && continue
	echo -en "\n${x[$a]}${x[$b]}${x[$c]}X: "
	for d in {0..15}; do
		echo -en "\u${x[$a]}${x[$b]}${x[$c]}${x[$d]}"
	done
done; done; done
```

It prints all unicode chars. You can scroll it and find some working chars, that can be used in prefixes. You can edit prefixes in `/home/$USER/.config/ptSh/config`
