### ISSUE TITLE
ptwd error on macos [BUG]

### ISSUE THREAD

**Issue by grayalas** [jszczerbinsky/ptSh#27]
**Describe the bug**
After installing on macos and following macos specific install instrucions (installing bash and coreutils and updating PATH in .zshrc) all other aliases work fine except for ptwd. When ptwd alias is included in .zshrc the terminal doesn't load propperly.

**To Reproduce**
Follow install steps in [wiki](https://github.com/jszczerbinsky/ptSh/wiki/1.-Installation#installing-on-macos) and add `alias pwd="~/.local/bin/ptpwd"` to .zshrc

**Expected behavior**
pretty ptwd

**Screenshots/terminal output**
<img width="352" alt="Screen Shot 2021-05-14 at 10 42 31 AM" src="https://user-images.githubusercontent.com/22018852/118196590-61e40580-b4a1-11eb-8756-9b8106baf696.png">

<img width="404" alt="Screen Shot 2021-05-14 at 10 40 20 AM" src="https://user-images.githubusercontent.com/22018852/118196615-6c060400-b4a1-11eb-8d0b-5d9cd44de62a.png">

**Desktop**
MacOS

(loving ptSh thank you for sharing this!)

**Comment by naowalrahman** [comment]
One suggestion i have for you is, rather than making the alias call the program directly, add `~/.local/bin` to your path by doing
```zsh
export PATH=$HOME/.local/bin:$PATH
```
This will add `~/.local/bin` to your path. Then, alias pwd (as well as the other commands accordingly) to just ptpwd, like so:
```zsh
alias pwd="ptpwd"
```
This is a possible fix that I can think of.

**Comment by jszczerbinsky** [comment]
Closing, because all scripts has been replaced with programs in latest release
