### ISSUE TITLE
Feature suggestion for ptls

### ISSUE THREAD

**Issue by naowalrahman** [jszczerbinsky/ptSh#31]
Just a suggestion for ptls: make it so that ptls can take directories in arguments. Currently, in order to display the contents of a directory with ptls, you need to be in the directory. However, with ls, you can give directories as arguments, like: 
```zsh
ls ~/Documents
```
Thus you don't need to be in a specific directory to display the contents of it. This feature would be very nice to have in ptls!

**Comment by jszczerbinsky** [comment]
I know, it will be done soon
