### ISSUE TITLE
ptsh error on macos

### ISSUE THREAD

**Issue by arinn1204** [jszczerbinsky/ptSh#34]
**Describe the bug**
When running ptls I receive this error
`$HOME/.local/bin/ptls: line 91: -1: substring expression < 0`

Also (not sure if related but)
When running `pttouch 'foo'` I receive the output

pttouch 'foo'
│ foo
│└readlink: illegal option -- e
│usage: readlink [-n] [file ...]
│  Done

The images are also missing, however that is addressed in another open issue

**To Reproduce**
run ptls in either bash or zsh

**Expected behavior**
pretty ptwd

Desktop
MacOS

Shell
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
zsh 5.8 (x86_64-apple-darwin20.0)

Versions tried:
(commit) 737685cf64dcd00572d3997a6f2b514219156288
(tag) v0.2-alpha

**Comment by jszczerbinsky** [comment]
Duplicate
Check out: https://github.com/jszczerbinsky/ptSh/issues/23
