### ISSUE TITLE
[BUG] Receiving ptSh does not exist

### ISSUE THREAD

**Issue by machooper** [jszczerbinsky/ptSh#35]
**Describe the bug**
I ran the install script and received the error at the end of the script output (output below), then I tried to install manually and run into the same error. I have exported the location to the path as instructed.

**To Reproduce**
Download install script and run.

**Expected behavior**
Install script to run and tool to run without issues.

**Screenshots/terminal output**
```
Cloning into '/tmp/ptSh/v0.2-alpha'...
remote: Enumerating objects: 454, done.
remote: Counting objects: 100% (454/454), done.
remote: Compressing objects: 100% (276/276), done.
remote: Total 454 (delta 276), reused 323 (delta 173), pack-reused 0
Receiving objects: 100% (454/454), 102.56 KiB | 1.14 MiB/s, done.
Resolving deltas: 100% (276/276), done.
HEAD is now at 02d3d7a Merge pull request #21 from 18fadly-anthony/main
Installing...
Version: v0.2-alpha
./install.sh: line 15: ptsh: command not found

```

**Desktop**
 - Arch Linux Arm
 - ZSH Shell (also tried on Bash, same error)

**Comment by jszczerbinsky** [comment]
It looks like something is wrong with $PATH, make sure, that `export PATH=~/.local/bin:$PATH` is in your .zshrc and show output of `echo $PATH`

**Comment by machooper** [comment]
`echo $PATH`  
returns 
```
/home/mac/.local/bin:/home/mac/.local/bin:/home/mac/.local/bin:/home/mac/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/vc/sbin:/opt/vc/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

**Comment by jszczerbinsky** [comment]
Did you run `install.sh `as root? If you did, ptSh will be installed for root, not your user. Are ptsh scripts in `~/.local/bin`?

**Comment by jszczerbinsky** [comment]
Make sure, that ptSh scripts are in `~/.local/bin` directory and they are executable

**Comment by machooper** [comment]
This fixed the issue, sorry for long response. 

For some reason the script wasn't copying or moving the binaries to the path, I manually moved them and this fixed the issue.
