### ISSUE TITLE
[BUG] added space in error messages

### ISSUE THREAD

**Issue by wouu** [jszczerbinsky/ptSh#40]
**Describe the bug**
when a ptsh command results in an error, the error message is prepended with a space

**To Reproduce**
run a ptsh command that you know will result in error, optionally compare the terminal output to a ptsh command that results in success

**Expected behavior**
the error message does not have a space prepended to it, making it consistent with the success output.

**Screenshots/terminal output**
![image](https://user-images.githubusercontent.com/89600701/131554560-f43ccbf4-6ad5-47f6-ac96-4d1a2c00b4c0.png)

**Desktop**
 - OS/Linux distro: linux mint

**Comment by jszczerbinsky** [comment]
Closing, because all scripts has been replaced with programs in latest release
