### ISSUE TITLE
[BUG] ls with specified path only shows contents of ~/

### ISSUE THREAD

**Issue by antz22** [jszczerbinsky/ptSh#42]
**Describe the bug**
When using the 'ls' command with 'source ptSh_set_aliases' in ~/.zshrc (for zsh shell), it lists the contents of the home ~/ directory rather than the contents of the directory specified.

**To Reproduce**
ls [path/to/directory]

**Expected behavior**
The contents of the directory should be listed out, rather than the contents of the home directory.

**Screenshots/terminal output**
![2021-10-27_21-09](https://user-images.githubusercontent.com/59377837/139169113-32069fd9-af18-4ee6-b128-49fafe8a25b8.png)

With 'source ptSh_set_aliases' removed from the ~/.zshrc, here is the result.

![2021-10-27_21-13](https://user-images.githubusercontent.com/59377837/139169358-602b1c35-0789-4983-bf9f-c1fb5f542507.png)

**Desktop**
 OS: Arch  Linux

**Comment by Al3bad** [comment]
I was able to fix the bug in this pull request #43

**Comment by Sad-Shogun** [comment]
I am having the same issue on arch linux as well. I defined the aliases myself in my zshrc and ls only lists files and directories in the cwd.

**Comment by jszczerbinsky** [comment]
Closing, because all scripts has been replaced with programs
