### ISSUE TITLE
Disable SIP?

### ISSUE THREAD

**Issue by choicelildice** [jszczerbinsky/ptSh#5]
Does this require you to disable SIP? I cloned the repository, and when I ran `make`: 
`sudo mkdir -p /usr/share/ptSh
mkdir: /usr/share/ptSh: Operation not permitted
make: *** [install] Error 1`

Upon Googling, it looks like this should maybe install to `usr/local/` instead of `usr/share`? Not sure.

**Comment by jszczerbinsky** [comment]
Yeah, I've done some research and it should be in `/usr/local`, I will fix it in a moment
