### ISSUE TITLE
[BUG] ptcp cuts off first letter of file name

### ISSUE THREAD

**Issue by gianmarcogg03** [jszczerbinsky/ptSh#52]
**Describe the bug**
When I copy a file with ptcp the copy has the first letter of the original name cut off, so if for example I copy the file "hello" in another folder, the copy will be called "ello".

**To Reproduce**
ptcp a file into another directory.

**Expected behavior**
The copy should have the proper name.

**Screenshots/terminal output**
![image](https://user-images.githubusercontent.com/28053717/160766168-b30f106b-5bc1-47e6-addd-23408644c8fc.png)

**Desktop**
 - OS/Linux distro: Arch Linux

**Comment by jszczerbinsky** [comment]
Okay, I fixed it. Check out a new release: [v0.3.2-beta](https://github.com/jszczerbinsky/ptSh/releases/tag/v0.3.2-beta)

**Comment by gianmarcogg03** [comment]
Perfect, thanks.
